name: CI

on: [pull_request]

jobs:
  hub-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: tests
        run: ./scripts/tests.sh
  push-hub:
    runs-on: ubuntu-latest
    container:
      image: jinaai/jina:master
      options: "--entrypoint /bin/bash"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: push
        run: jina hub push --force ${{ secrets.HUBBLE_UUID }} --secret ${{ secrets.HUBBLE_SECRET }} .